### ISSUE TITLE
invoke.Context().run() regression on 0.12.0

### ISSUE THREAD

**Issue by thebjorn** [pyinvoke/invoke#311]
My guess would be that select.select is used on something that is not a socket (which doesn't work under windows, without looking at the code I would guess that WaitForMultipleObjects is what you're looking for).

(fyi:, `import socket` calls WSAStartup..)

```
(dktasklib) go|w:\srv\tmp> inv --version
Invoke 0.11.0

(dktasklib) go|w:\srv\tmp> python
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import invoke
>>> invoke.Context().run('type foo.txt')
Content of foo.txt
<invoke.runners.Result object at 0x046106D0>
>>> ^Z


(dktasklib) go|w:\srv\tmp> pip install -U invoke
You are using pip version 7.1.0, however version 8.0.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Collecting invoke
  Using cached invoke-0.12.0-py2.py3-none-any.whl
Installing collected packages: invoke
  Found existing installation: invoke 0.11.0
    Uninstalling invoke-0.11.0:
      Successfully uninstalled invoke-0.11.0
Successfully installed invoke-0.12.0

(dktasklib) go|w:\srv\tmp> python
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import invoke
>>> invoke.Context().run('type foo.txt')
Content of foo.txt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "w:\srv\venv\dktasklib\lib\site-packages\invoke\context.py", line 53, in run
    return runner_class(context=self).run(command, **kwargs)
  File "w:\srv\venv\dktasklib\lib\site-packages\invoke\runners.py", line 232, in run
    raise ThreadException(exceptions)
invoke.exceptions.ThreadException:
Saw 1 exceptions within threads (error):


Thread args: {'kwargs': {'input_': <open file '<stdin>', mode 'r' at 0x007AD020>},
 'target': <bound method Local.handle_stdin of <invoke.runners.Local object at 0x04731370>>}

Traceback (most recent call last):

  File "w:\srv\venv\dktasklib\lib\site-packages\invoke\runners.py", line 804, in run
    super(_IOThread, self).run()

  File "C:\Python27\Lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)

  File "w:\srv\venv\dktasklib\lib\site-packages\invoke\runners.py", line 411, in handle_stdin
    reads, _, _ = select.select([input_], [], [], 0.0)

error: (10093, 'Either the application has not called WSAStartup, or WSAStartup failed')


>>> import socket
>>> invoke.Context().run('type foo.txt')
Content of foo.txt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "w:\srv\venv\dktasklib\lib\site-packages\invoke\context.py", line 53, in run
    return runner_class(context=self).run(command, **kwargs)
  File "w:\srv\venv\dktasklib\lib\site-packages\invoke\runners.py", line 232, in run
    raise ThreadException(exceptions)
invoke.exceptions.ThreadException:
Saw 1 exceptions within threads (error):


Thread args: {'kwargs': {'input_': <open file '<stdin>', mode 'r' at 0x007AD020>},
 'target': <bound method Local.handle_stdin of <invoke.runners.Local object at 0x04731350>>}

Traceback (most recent call last):

  File "w:\srv\venv\dktasklib\lib\site-packages\invoke\runners.py", line 804, in run
    super(_IOThread, self).run()

  File "C:\Python27\Lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)

  File "w:\srv\venv\dktasklib\lib\site-packages\invoke\runners.py", line 411, in handle_stdin
    reads, _, _ = select.select([input_], [], [], 0.0)

error: (10038, 'An operation was attempted on something that is not a socket')


>>>
```

**Comment by bitprophet** [comment]
This duplicates #302 I believe, thanks! See discussion on #304 and #289 too :)
