### ISSUE TITLE
0.12 doesn't stop started process with Ctrl+C

### ISSUE THREAD

**Issue by presidento** [pyinvoke/invoke#315]
In version 0.12 pressing Ctrl+C causes an exception and the started docker image doesn't stop. I have tried to reproduce it with more common programs, like bash or sleep, but I couldn't.

```
from invoke import ctask

@ctask
def docker_sleep(ctx):
   ctx.run('docker run ubuntu sleep 10000')
```

You can check that it is running via `docker ps`. Pressing Ctrl+C gives the following exception and keeps the started process running:

```
Traceback (most recent call last):
  File "/usr/local/bin/inv", line 9, in <module>
    load_entry_point('invoke', 'console_scripts', 'inv')()
  File "/home/matefarkas/work/invoke/invoke/program.py", line 270, in run
    self.execute()
  File "/home/matefarkas/work/invoke/invoke/program.py", line 379, in execute
    executor.execute(*self.tasks)
  File "/home/matefarkas/work/invoke/invoke/executor.py", line 114, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/matefarkas/work/invoke/invoke/tasks.py", line 113, in __call__
    result = self.body(*args, **kwargs)
  File "/home/matefarkas/work/invoke/2/tasks.py", line 5, in sleep
    ctx.run('docker run ubuntu sleep 10000')
  File "/home/matefarkas/work/invoke/invoke/context.py", line 53, in run
    return runner_class(context=self).run(command, **kwargs)
  File "/home/matefarkas/work/invoke/invoke/runners.py", line 222, in run
    self.wait()
  File "/home/matefarkas/work/invoke/invoke/runners.py", line 710, in wait
    self.process.wait()
  File "/usr/lib/python3.5/subprocess.py", line 1647, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.5/subprocess.py", line 1597, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

It worked perfectly with 0.11.1: there was no exception and the docker process stopped before Invoke exited with exit code 130.

**Comment by bitprophet** [comment]
Can you retry this with master (or 0.12.2 if I get it out soon, hoping to) now that #303 got merged? Wondering if it's related.

**Comment by presidento** [comment]
It is still not works. :(

Pressing Ctrl+C does not do anything, pressing it again gives the following exception and the program (docker in my case) remain running. (It was stopped with 0.11.1.)

```
$ invoke sleep

^CTraceback (most recent call last):
  File "/usr/local/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/home/matefarkas/work/invoke/invoke/program.py", line 270, in run
    self.execute()
  File "/home/matefarkas/work/invoke/invoke/program.py", line 379, in execute
    executor.execute(*self.tasks)
  File "/home/matefarkas/work/invoke/invoke/executor.py", line 114, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/matefarkas/work/invoke/invoke/tasks.py", line 113, in __call__
    result = self.body(*args, **kwargs)
  File "/home/matefarkas/work/invoke/2/tasks.py", line 5, in sleep
    ctx.run('docker run ubuntu sleep 10000')
  File "/home/matefarkas/work/invoke/invoke/context.py", line 53, in run
    return runner_class(context=self).run(command, **kwargs)
  File "/home/matefarkas/work/invoke/invoke/runners.py", line 269, in run
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by bitprophet** [comment]
Thanks, will see if I can recreate sometime. Maybe we need to try harder to ensure we send the interrupt to the subprocess, I'm not 100% sure how that's behaving right now. It definitely works for other long-running local subprocesses though (see the use of `python -m http.server` in #303) so wondering if this is something specific docker is doing.

**Comment by presidento** [comment]
I think it was a bug in docker, not in Invoke, it has been fixed in [Docker version 0.10](https://github.com/docker/docker/blob/v0.10.0/CHANGELOG.md). And I couldn't reproduce it with any application but Docker version 0.9, so I close this issue as outdated.

**Comment by noirbizarre** [comment]
I'm experiencing this issue with every command so I don't think this is Docker related.

**Comment by svetlyak40wt** [comment]
I've checked, and Ctrl+C works perfectly in invoke==0.11.1.

**Comment by bitprophet** [comment]
@noirbizarre a) which version(s) of Invoke have you tried so far and b) can you provide some of the specific commands you've had the issue with? As noted above, this doesn't appear to be a blanket issue affecting all users, so more info is better.

**Comment by bitprophet** [comment]
Also @svetlyak40wt are you just noting that you don't have this on 0.11.1, or is the implication that you've also gotten the problem to appear on 0.12.x?

**Comment by bitprophet** [comment]
Note to self, the "shouldn't we pass ctrl-c to subprocess better" behavior I mentioned earlier seems to have its own ticket, #152.

**Comment by svetlyak40wt** [comment]
Yes, I've gotten this issue on 0.12.x.

**Comment by bitprophet** [comment]
This is out in 0.13, please upgrade. Was listed in changelog under #152.
