### ISSUE TITLE
invoke fails to import in Python3

### ISSUE THREAD

**Issue by nicholastulach** [pyinvoke/invoke#333]
(Sorry if i'm not following a particular bug report convention. I'm kind of new here.)

I installed invoke using `pip3 install invoke` and am trying to use it with a name generator library called `cumberbatch` (which i also installed with `pip3 install`. 

Using: python 3.5.1, invoke 0.12.2, and cumberbatch 0.5

Command: `invoke build`
Alternate: `python3 tasks.py`

The following `tasks.py` code sample illustrates what i'm trying to do.

    from invoke import task
    import cumberbatch

    @task
    def build():
        print(cumberbatch.first())

    if __name__ == '__main__':
        build()

The command gives the following error. It works when executed with the alternate command:

    Traceback (most recent call last):
      File "/usr/local/bin/invoke", line 11, in <module>
        sys.exit(program.run())
      File "/usr/local/lib/python3.5/site-packages/invoke/program.py", line 269, in run
        self._parse(argv)
      File "/usr/local/lib/python3.5/site-packages/invoke/program.py", line 323, in _parse
        self.load_collection()
      File "/usr/local/lib/python3.5/site-packages/invoke/program.py", line 471, in load_collection
        coll = loader.load(coll_name) if coll_name else loader.load()
      File "/usr/local/lib/python3.5/site-packages/invoke/loader.py", line 53, in load
        module = imp.load_module(name, fd, path, desc)
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 234, in load_module
        return load_source(name, filename, file)
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/imp.py", line 172, in load_source
        module = _load(spec)
      File "<frozen importlib._bootstrap>", line 693, in _load
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 662, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/Users/nkt/Work/test/tasks.py", line 1, in <module>
        import cumberbatch
    ImportError: No module named 'cumberbatch'

**Comment by presidento** [comment]
It should work. Is `cumberbatch` installed successfully? (Is it amoung `pip3 list`?)

**Comment by nicholastulach** [comment]
Yes. It works when i call the `__main__` of the included file, but it doesn't work with `invoke build`.

**Comment by presidento** [comment]
Please, create a task where you just print the Python version. I think, `invoke build` uses a different one.

```python
@task
def version():
  import sys
  print(sys.version)
```

**Comment by nicholastulach** [comment]
my-computer:test nkt$ invoke version
    3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
    [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

**Comment by nicholastulach** [comment]
Definitely something goofy in my environment because when i run it in a Docker container, it works. :(

Sorry for the distraction.

**Comment by presidento** [comment]
Can you close the issue?
