### ISSUE TITLE
Hiding tasks from --list which are pre/post methods

### ISSUE THREAD

**Issue by socketubs** [pyinvoke/invoke#348]
Very similar to #290 but the workaround proposed by @bitprophet doesn't work for pre/post methods.

I get this output:

```python
Traceback (most recent call last):
  File "[path]/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "[path]/invoke/program.py", line 270, in run
    self.execute()
  File "[path]/invoke/program.py", line 379, in execute
    executor.execute(*self.tasks)
  File "[path]/invoke/executor.py", line 97, in execute
    expanded = self.expand_calls(calls, config)
  File "[path]/invoke/executor.py", line 188, in expand_calls
    ret.extend(self.expand_calls(call.pre, config))
  File "[path]/invoke/executor.py", line 180, in expand_calls
    if call.contextualized:
AttributeError: 'function' object has no attribute 'contextualized'
```

With this source:

```python
from invoke import task

def pre_task():
    pass

@task(pre=[pre_task])
def my_task():
    pass
```

**Comment by socketubs** [comment]
Just realized that underscore prefixed tasks are not listed. Am I wrong?

**Comment by dirkschneemann** [comment]
Doesn't work for me on `invoke 0.15.0`, underscore prefixed tasks are still listed (at the top of the list since they are in alphabetical order).

This feature would be much appreciated since I have some pre- and post-tasks which I do not want to flood the task list with (they are not meant to be executed on their own anyway).

**Comment by bitprophet** [comment]
- `pre_task()` needs to be an actual `@task` (and both functions need an initial `context` argument, at least in modern Invoke, see the changelog for when that changed) - that's the proximate cause of the error here.
- It's possible at some point leading underscores caused tasks to be hidden or not registered correctly, but I don't think that was ever on purpose and it's probably been fixed since, if it existed.
- I acknowledge the overall feature request, though I don't think it makes sense for pre/post tasks to be hidden by default - much of the time, the entire point of structuring things as pre/post tasks and not simply "call subroutine from inside task body" is so that the 'subroutines' show up as independently callable tasks!
- I think what you really want instead is something like `@task(hidden=True)`, allowing something to be listed as a task for purposes of dependency management and deduplication (i.e. if it were in the main task's body, it'd run every time the main task does, disallowing deduplication/caching - see also #461 which expands that feature set) but where you indicate that it's not intended for direct execution.

**Comment by danieleteti** [comment]
Any news on this? It would be really useful for dependency management and deduplication

**Comment by rberger** [comment]
Having `@task(hidden=True)` would be awesome

**Comment by SnoopJ** [comment]
I believe this feature request is also covered by #722 (that one being a later duplicate of this one) and would be closed by merge of #723.
