### ISSUE TITLE
Travis:  TypeError: Tasks must have an initial Context argument! #409

### ISSUE THREAD

**Issue by assem-ch** [pyinvoke/invoke#367]
My invoke commands are failing in travis cause the lack of an initial Context argument. How could I resolve this. 

```

 $ sudo pip install invoke
The directory '/home/travis/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/travis/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting invoke
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading invoke-0.13.0-py2-none-any.whl (123kB)
    100% |████████████████████████████████| 126kB 1.9MB/s 
Installing collected packages: invoke
Successfully installed invoke-0.13.0
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
0.11s$ invoke download
Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 269, in run
    self._parse(argv)
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 325, in _parse
    self.load_collection()
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 473, in load_collection
    coll = loader.load(coll_name) if coll_name else loader.load()
  File "/usr/local/lib/python2.7/dist-packages/invoke/loader.py", line 53, in load
    module = imp.load_module(name, fd, path, desc)
  File "/home/travis/build/ioGrow/iogrowCRM/tasks.py", line 24, in <module>
    @task(default=True)
  File "/usr/local/lib/python2.7/dist-packages/invoke/tasks.py", line 303, in inner
    autoprint=autoprint,
  File "/usr/local/lib/python2.7/dist-packages/invoke/tasks.py", line 58, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/usr/local/lib/python2.7/dist-packages/invoke/tasks.py", line 149, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/usr/local/lib/python2.7/dist-packages/invoke/tasks.py", line 144, in argspec
    raise TypeError("Tasks must have an initial Context argument!")
TypeError: Tasks must have an initial Context argument! 
```

**Comment by darioblanco** [comment]
Invoke 0.13.0 had a backwards incompatible change regarding contextualized tasks. All the tasks are now contextualized (you can check the backlog and review the documentation).

Add the "ctx" parameter to all your tasks and it will be fixed

**Comment by bitprophet** [comment]
Thanks @darioblanco!
