### ISSUE TITLE
Invoke 0.12 breaks on Windows.

### ISSUE THREAD

**Issue by MinchinWeb** [pyinvoke/invoke#370]
I define a simple task:
```
@task
def test():
    run('dir')
```

This task prints a directory listing.

On Windows 10 with Invoke 0.11.0, it runs fine. With Invoke 0.12.0, it breaks.

With Invoke 0.12, displays the results of the directory listing, and then the following traceback:
```
Traceback (most recent call last):
  File "c:\program files\python 3.5\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python 3.5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python 3.5\Scripts\invoke.exe\__main__.py", line 9, in <module>
  File "c:\program files\python 3.5\lib\site-packages\invoke\program.py", line 270, in run
    self.execute()
  File "c:\program files\python 3.5\lib\site-packages\invoke\program.py", line 379, in execute
    executor.execute(*self.tasks)
  File "c:\program files\python 3.5\lib\site-packages\invoke\executor.py", line 114, in execute
    result = call.task(*args, **call.kwargs)
  File "c:\program files\python 3.5\lib\site-packages\invoke\tasks.py", line 113, in __call__
    result = self.body(*args, **kwargs)
  File "S:\Documents\GitHub\blog.minchin.ca-pelican\tasks.py", line 106, in test
    run('dir')
  File "c:\program files\python 3.5\lib\site-packages\invoke\__init__.py", line 27, in run
    return Context().run(command, **kwargs)
  File "c:\program files\python 3.5\lib\site-packages\invoke\context.py", line 53, in run
    return runner_class(context=self).run(command, **kwargs)
  File "c:\program files\python 3.5\lib\site-packages\invoke\runners.py", line 232, in run
    raise ThreadException(exceptions)
invoke.exceptions.ThreadException: 
Saw 1 exceptions within threads (OSError):


Thread args: {'kwargs': {'input_': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='cp850'>},
 'target': <bound method Runner.handle_stdin of <invoke.runners.Local object at 0x00000262578D5358>>}

Traceback (most recent call last):

  File "c:\program files\python 3.5\lib\site-packages\invoke\runners.py", line 804, in run
    super(_IOThread, self).run()

  File "c:\program files\python 3.5\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)

  File "c:\program files\python 3.5\lib\site-packages\invoke\runners.py", line 411, in handle_stdin
    reads, _, _ = select.select([input_], [], [], 0.0)

OSError: [WinError 10093] Either the application has not called WSAStartup, or WSAStartup failed
```

The error seems to be Windows related.

Note that if the task in questions just does "python-y things" (i.e doesn't try to run shell commands), it works fine.

**Comment by bitprophet** [comment]
Ah, looks like this is #302. Should've been fixed in a recent release - I see you also posted an 0.13 related ticket so I assume you upgraded and got past this? Gonna close for now, thanks!

**Comment by MinchinWeb** [comment]
Thanks for the prompt response. At the time I hadn't gotten either v0.12 or v0.13 working, but I think I have v0.13 working now.
