### ISSUE TITLE
run() failing on Windows

### ISSUE THREAD

**Issue by pfmoore** [pyinvoke/invoke#387]
I've just upgraded from 0.12.2 to 0.13. The following simple task works fails:
```python
from invoke import task

@task
def hello(ctx):
    ctx.run("echo Hello, world!")
```
The error is

```
>inv hello
Traceback (most recent call last):
  File "c:\users\uk03306\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\uk03306\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\UK03306\AppData\Local\Programs\Python\Python35\Scripts\inv.exe\__main__.py", line 9, in <module>
  File "c:\users\uk03306\appdata\local\programs\python\python35\lib\site-packages\invoke\program.py", line 270, in run
    self.execute()
  File "c:\users\uk03306\appdata\local\programs\python\python35\lib\site-packages\invoke\program.py", line 381, in execute
    executor.execute(*self.tasks)
  File "c:\users\uk03306\appdata\local\programs\python\python35\lib\site-packages\invoke\executor.py", line 113, in execute
    result = call.task(*args, **call.kwargs)
  File "c:\users\uk03306\appdata\local\programs\python\python35\lib\site-packages\invoke\tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "C:\Work\Scratch\cs\tasks.py", line 5, in hello
    ctx.run("echo Hello, world!")
  File "c:\users\uk03306\appdata\local\programs\python\python35\lib\site-packages\invoke\context.py", line 53, in run
    return runner_class(context=self).run(command, **kwargs)
  File "c:\users\uk03306\appdata\local\programs\python\python35\lib\site-packages\invoke\runners.py", line 259, in run
    self.start(command, shell, env)
  File "c:\users\uk03306\appdata\local\programs\python\python35\lib\site-packages\invoke\runners.py", line 966, in start
    stdin=PIPE,
  File "c:\users\uk03306\appdata\local\programs\python\python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "c:\users\uk03306\appdata\local\programs\python\python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 3] The system cannot find the path specified
```

It looks like the problem is in runners.py, ```Local.start``` which has the call
```
            self.process = Popen(
                command,
                shell=True,
                executable=shell,
                env=env,
                stdout=PIPE,
                stderr=PIPE,
                stdin=PIPE,
            )
```

If the user doesn't set a shell, it gets set by default to ```/bin/bash```. This is clearly wrong for Windows. Surely it would be better to omit ```executable``` unless the user explicitly overrides?

I'll try to find some time to put together a PR, but why wasn't this picked up by the appveyor tests? I would have expected a pretty obvious failure (although I can't find a link to the latest CI runs in github, so I can't check what's actually happening...)

**Comment by bitprophet** [comment]
This is #345 I believe! An actual patch for it is still pending, partly because there's a config workaround.

**Comment by pfmoore** [comment]
Nice - thanks for the pointer. I looked before posting this but didn't spot #345 (not sure why, it should have been obvious from the title, sorry!)
