### ISSUE TITLE
Starting Server Produces Invoke Error "Tasks must have an initial Context Argument!"

### ISSUE THREAD

**Issue by donavynelliott** [pyinvoke/invoke#389]
`Exit code: 1

Stderr:

Traceback (most recent call last):
  File "/home/redactedadmin/venv-django/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/home/redactedadmin/venv-django/local/lib/python2.7/site-packages/invoke/program.py", line 269, in run
    self._parse(argv)
  File "/home/redactedadmin/venv-django/local/lib/python2.7/site-packages/invoke/program.py", line 325, in _parse
    self.load_collection()
  File "/home/redactedadmin/venv-django/local/lib/python2.7/site-packages/invoke/program.py", line 473, in load_collection
    coll = loader.load(coll_name) if coll_name else loader.load()
  File "/home/redactedadmin/venv-django/local/lib/python2.7/site-packages/invoke/loader.py", line 53, in load
    module = imp.load_module(name, fd, path, desc)
  File "/home/redactedadmin/venv-django/local/lib/python2.7/site-packages/wger/tasks.py", line 283, in <module>
    @task
  File "/home/redactedadmin/venv-django/local/lib/python2.7/site-packages/invoke/tasks.py", line 267, in task
    return Task(args[0], **kwargs)
  File "/home/redactedadmin/venv-django/local/lib/python2.7/site-packages/invoke/tasks.py", line 58, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/home/redactedadmin/venv-django/local/lib/python2.7/site-packages/invoke/tasks.py", line 149, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/home/redactedadmin/venv-django/local/lib/python2.7/site-packages/invoke/tasks.py", line 144, in argspec
    raise TypeError("Tasks must have an initial Context argument!")
TypeError: Tasks must have an initial Context argument!
`

This error occurs when attempting to run wger. I fixed this my downgrading the version of pyinvoke I had installed via

`pip install invoke=0.12.2`

I don't exactly understand what is going on here.

**Comment by bitprophet** [comment]
Please read [the changelog](http://www.paramiko.org/changelog.html) before upgrading! We carefully note backwards incompatible changes there in big red warning blocks :) thanks!
