### ISSUE TITLE
Don't hide bugs in tests (UnicodeEncodeError when trying to execute a non-ascii command in non-utf8 locale)

### ISSUE THREAD

**Issue by frol** [pyinvoke/invoke#404]
Using `@only_utf8` decorators implies that users cannot safely use invoke in environments where UTF-8 is not used by default or available (Windows OS and minimized Linux distros):

* https://github.com/pyinvoke/invoke/blob/master/integration/main.py#L92
* https://github.com/pyinvoke/invoke/blob/master/integration/main.py#L99
* https://github.com/pyinvoke/invoke/blob/master/integration/main.py#L105

Removing these decorators and running the integration tests with `LANG=C` (`env LANG=C invoke integration`) reveals the bugs:

* #403 (or #275) - you will see that some of the tests after the failing ones are repeated several times!
* Once the previous bug is solved you will see the following:

```
======================================================================
ERROR: main.funky_characters_in_stdout.nonprinting_bytes
----------------------------------------------------------------------
  File "/usr/lib64/python3.5/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib64/python3.5/unittest/case.py", line 600, in run
    testMethod()
  File "/tmp/env3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/invoke/integration/main.py", line 101, in nonprinting_bytes
    run("echo '\xff'", hide='stderr', out_stream=self.bad_stdout)
  File "/tmp/invoke/invoke/__init__.py", line 38, in run
    return Context().run(command, **kwargs)
  File "/tmp/invoke/invoke/context.py", line 60, in run
    return runner_class(context=self).run(command, **kwargs)
  File "/tmp/invoke/invoke/runners.py", line 267, in run
    return self._run_body(command, **kwargs)
  File "/tmp/invoke/invoke/runners.py", line 281, in _run_body
    self.start(command, shell, env)
  File "/tmp/invoke/invoke/runners.py", line 996, in start
    stdin=PIPE,
  File "/usr/lib64/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.5/subprocess.py", line 1490, in _execute_child
    restore_signals, start_new_session, preexec_fn)
'ascii' codec can't encode character '\xff' in position 6: ordinal not in range(128)
-------------------- >> begin captured logging << --------------------
invoke.config._load_file: Didn't see any /etc/invoke.yaml, skipping.
invoke.config._load_file: Didn't see any /etc/invoke.json, skipping.
invoke.config._load_file: Didn't see any /home/frol/.invoke.yaml, skipping.
invoke.config._load_file: Didn't see any /home/frol/.invoke.json, skipping.
invoke.config.merge: Merging config sources in order...
invoke.config.merge: Defaults: {'sudo': {'password': None, 'prompt': '[sudo] password: '}, 'run': {'echo': False, 'hide': None, 'out_stream': None, 'env': {}, 'encoding': None, 'watchers': [], 'pty': False, 'err_stream': None, 'warn': False, 'fallback': True, 'shell': '/bin/bash', 'in_stream': None, 'replace_env': False, 'echo_stdin': None}, 'tasks': {'dedupe': True}}
invoke.config.merge: Collection-driven: {}
invoke.config._merge_file: System-wide config file (/etc/invoke.py): {}
invoke.config._merge_file: Per-user config file (/home/frol/.invoke.py): {}
invoke.config._merge_file: Per-project config file has not been loaded yet, skipping
invoke.config.merge: Environment variable config: {}
invoke.config._merge_file: Runtime config file has not been loaded yet, skipping
invoke.config.merge: Overrides: {}
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: main.funky_characters_in_stdout.nonprinting_bytes_pty
----------------------------------------------------------------------
  File "/usr/lib64/python3.5/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib64/python3.5/unittest/case.py", line 600, in run
    testMethod()
  File "/tmp/env3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/invoke/integration/main.py", line 108, in nonprinting_bytes_pty
    out_stream=self.bad_stdout)
  File "/tmp/invoke/invoke/__init__.py", line 38, in run
    return Context().run(command, **kwargs)
  File "/tmp/invoke/invoke/context.py", line 60, in run
    return runner_class(context=self).run(command, **kwargs)
  File "/tmp/invoke/invoke/runners.py", line 267, in run
    return self._run_body(command, **kwargs)
  File "/tmp/invoke/invoke/runners.py", line 408, in _run_body
    raise UnexpectedExit(result)
Encountered a bad command exit code!

Command: "echo '\xff'"

Exit code: 1

Stdout (pty=True; no stderr possible):

Traceback (most recent call last):
  File "/tmp/invoke/invoke/runners.py", line 978, in start
    os.execve(shell, [shell, '-c', command], env)
UnicodeEncodeError: 'ascii' codec can't encode character '\xff' in position 6: ordinal not in range(128)



-------------------- >> begin captured logging << --------------------
invoke.config._load_file: Didn't see any /etc/invoke.yaml, skipping.
invoke.config._load_file: Didn't see any /etc/invoke.json, skipping.
invoke.config._load_file: Didn't see any /home/frol/.invoke.yaml, skipping.
invoke.config._load_file: Didn't see any /home/frol/.invoke.json, skipping.
invoke.config.merge: Merging config sources in order...
invoke.config.merge: Defaults: {'sudo': {'password': None, 'prompt': '[sudo] password: '}, 'run': {'echo': False, 'hide': None, 'out_stream': None, 'env': {}, 'encoding': None, 'watchers': [], 'pty': False, 'err_stream': None, 'warn': False, 'fallback': True, 'shell': '/bin/bash', 'in_stream': None, 'replace_env': False, 'echo_stdin': None}, 'tasks': {'dedupe': True}}
invoke.config.merge: Collection-driven: {}
invoke.config._merge_file: System-wide config file (/etc/invoke.py): {}
invoke.config._merge_file: Per-user config file (/home/frol/.invoke.py): {}
invoke.config._merge_file: Per-project config file has not been loaded yet, skipping
invoke.config.merge: Environment variable config: {}
invoke.config._merge_file: Runtime config file has not been loaded yet, skipping
invoke.config.merge: Overrides: {}
--------------------- >> end captured logging << ---------------------
Ran 27 tests in 7.649 seconds
FAILED (failures=0, errors=2, skipped=2)
```

**Comment by johnraz** [comment]
@bitprophet this one should be labelled.
