### ISSUE TITLE
invoke fails to import in Python3

### ISSUE THREAD

**Issue by SwampFalc** [pyinvoke/invoke#428]
Since it's almost a year since #333 was closed and because that report did not contain that much information, I've preferred to create a new issue, but I'm basically running into the exact same problem: I'm trying to run invoke in python3 and it fails to import the contents of my tasks directory.

So, starting from my home directory:

1) ls -l tasks
```
-rw-r--r-- 1 root root 112 feb 10 17:10 __init__.py
-rw-r--r-- 1 root root 888 feb 10 16:59 lxc.py
```

2) cat tasks/__init__.py
```
from invoke import Collection

ns = Collection()

import sys
print(sys.path)

import lxc
ns.add_collection(lxc)
```
(The sys stuff was to try and see if the error came from there)

3) cat tasks/lxc.py
```
import invoke
import pylxd

@invoke.task
def set_ip(ctx, container, ip):
    interfaces = '{}'.format(ip)
    client = pylxd.Client()
    container = client.containers.get(container)
    container.files.put('/etc/network/interfaces', interfaces)
    container.execute(('ifdown', 'eth0'))
    container.execute(('ifup', 'eth0'))
```
(Removed the full template of my interfaces file)

4) invoke -l
```
['/root', '/usr/local/bin', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/usr/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/dist-packages', '/usr/lib/python3/dist-packages']
Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.5/dist-packages/invoke/program.py", line 273, in run
    self._parse(argv)
  File "/usr/local/lib/python3.5/dist-packages/invoke/program.py", line 333, in _parse
    self.load_collection()
  File "/usr/local/lib/python3.5/dist-packages/invoke/program.py", line 481, in load_collection
    coll = loader.load(coll_name) if coll_name else loader.load()
  File "/usr/local/lib/python3.5/dist-packages/invoke/loader.py", line 53, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/tasks/__init__.py", line 8, in <module>
    import lxc
ImportError: No module named 'lxc'
```

python 3.5.2, invoke 0.14.0

**Comment by SwampFalc** [comment]
And just to confirm, the exact same setup works fine if I run the python 2.7.12 version of invoke...

**Comment by SwampFalc** [comment]
Right, the guys at #python have helped me realize that in python 3, you can't do `import lxc` anymore, you need to do `from . import lxc`.

Works now.
