### ISSUE TITLE
Cannot disable stdin when running tasks

### ISSUE THREAD

**Issue by thedrow** [pyinvoke/invoke#460]
I'm using invoke to run command line programs during tests and stdout is captured by pytest.
I'm running the program in the following way:
```
run('kubectl version 2>/dev/null >/dev/null',
                    hide='both',
                    in_stream=False)
```
and I'm getting the following exception:
```
def _run_body(self, command, **kwargs):
    # Normalize kwargs w/ config
    opts, out_stream, err_stream, in_stream = self._run_opts(kwargs)
    shell = opts['shell']
    # Environment setup
    env = self.generate_env(opts['env'], opts['replace_env'])
    # Echo running command
    if opts['echo']:
        print("\033[1;37m{0}\033[0m".format(command))
    # Start executing the actual command (runs in background)
    self.start(command, shell, env)
    # Arrive at final encoding if neither config nor kwargs had one
    self.encoding = opts['encoding'] or self.default_encoding()
    # Set up IO thread parameters (format - body_func: {kwargs})
    stdout, stderr = [], []
    thread_args = {
        self.handle_stdout: {
            'buffer_': stdout,
            'hide': 'stdout' in opts['hide'],
            'output': out_stream,
        },
        # TODO: make this & related functionality optional, for users who
        # don't care about autoresponding & are encountering issues with
        # the stdin mirroring? Downside is it fragments expected behavior &
        # puts folks with true interactive use cases in a different support
        # class.
        self.handle_stdin: {
            'input_': in_stream,
            'output': out_stream,
            'echo': opts['echo_stdin'],
        }
    }
    if not self.using_pty:
        thread_args[self.handle_stderr] = {
            'buffer_': stderr,
            'hide': 'stderr' in opts['hide'],
            'output': err_stream,
        }
    # Kick off IO threads
    self.threads = {}
    exceptions = []
    for target, kwargs in six.iteritems(thread_args):
        t = ExceptionHandlingThread(target=target, kwargs=kwargs)
        self.threads[target] = t
        t.start()
    # Wait for completion, then tie things off & obtain result
    # And make sure we perform that tying off even if things asplode.
    exception = None
    while True:
        try:
            self.wait()
            break # done waiting!
        # NOTE: we handle all this now instead of at
        # actual-exception-handling time because otherwise the stdout/err
        # reader threads may block until the subprocess exits.
        # TODO: honor other signals sent to our own process and transmit
        # them to the subprocess before handling 'normally'.
        except KeyboardInterrupt as e:
            self.send_interrupt(e)
            # NOTE: no break; we want to return to self.wait()
        except BaseException as e: # Want to handle SystemExit etc still
            # Store exception for post-shutdown reraise
            exception = e
            # Break out of return-to-wait() loop - we want to shut down
            break
    # Inform stdin-mirroring worker to stop its eternal looping
    self.program_finished.set()
    # Join threads, setting a timeout if necessary
    for target, thread in six.iteritems(self.threads):
        thread.join(self._thread_timeout(target))
        e = thread.exception()
        if e is not None:
            exceptions.append(e)
    # If we got a main-thread exception while wait()ing, raise it now that
    # we've closed our worker threads.
    if exception is not None:
        raise exception
    # Strip out WatcherError from any thread exceptions; they are bundled
    # into Failure handling at the end.
    watcher_errors = []
    thread_exceptions = []
    for exception in exceptions:
        real = exception.value
        if isinstance(real, WatcherError):
            watcher_errors.append(real)
        else:
            thread_exceptions.append(exception)
    # If any exceptions appeared inside the threads, raise them now as an
    # aggregate exception object.
    if thread_exceptions:
>           raise ThreadException(thread_exceptions)
E           invoke.exceptions.ThreadException: 
E           Saw 1 exceptions within threads (AttributeError):
E           
E           
E           Thread args: {'kwargs': {'echo': None,
E                       'input_': False,
E                       'output': <_pytest.capture.EncodedFile object at 0x7f6d5f2f5400>},
E            'target': <bound method Runner.handle_stdin of <invoke.runners.Local object at 0x7f6d53734fd0>>}
E           
E           Traceback (most recent call last):
E           
E             File "/home/omer/Documents/Projects/myproject/.tox/py36-functional/lib/python3.6/site-packages/invoke/util.py", line 156, in run
E               super(ExceptionHandlingThread, self).run()
E           
E             File "/home/omer/.pyenv/versions/3.6.1/lib/python3.6/threading.py", line 864, in run
E               self._target(*self._args, **self._kwargs)
E           
E             File "/home/omer/Documents/Projects/myproject/.tox/py36-functional/lib/python3.6/site-packages/invoke/runners.py", line 632, in handle_stdin
E               data = self.read_our_stdin(input_)
E           
E             File "/home/omer/Documents/Projects/myproject/.tox/py36-functional/lib/python3.6/site-packages/invoke/runners.py", line 594, in read_our_stdin
E               bytes_ = input_.read(bytes_to_read(input_))
E           
E           AttributeError: 'bool' object has no attribute 'read'

.tox/py36-functional/lib/python3.6/site-packages/invoke/runners.py:353: ThreadException
```

It seems like invoke is still attempting to read from stdin even if it is disabled.

**Comment by bitprophet** [comment]
@thedrow Unfortunately that `False` option meaning to disable stdin, isn't available in anything but master at the moment (planning a release soon though, trying to close up a small related group of other new features first) - see how it's under the 'next release' header on the changelog, http://www.pyinvoke.org/changelog.html

If you get master, or wait a bit (maybe just later today hopefully) for 0.20, it should work after that upgrade. Thanks!
