### ISSUE TITLE
Encoding failure regression in 0.21 on windows

### ISSUE THREAD

**Issue by thebjorn** [pyinvoke/invoke#480]
The following test failure popped up when going from 0.20 to 0.21. I'm assuming, although I can't really follow the intentions in all the details, but it might have to do with 7b88eea53ae65ea7c9070e9a0854071d286c20e9 -- where you're not setting an error policy, e.g. `"ignore"`, at https://github.com/pyinvoke/invoke/commit/7b88eea53ae65ea7c9070e9a0854071d286c20e9#diff-120ba72c7bd4f71d0cbafe15108e00d2R118

stdio and encodings are quite finicky on windows, and `sys.getdefaultencoding()` is never the correct answer.  See e.g. this answer (https://stackoverflow.com/a/3259271/75103) for details.
```
================================== FAILURES ===================================
_________________________________ test_babel __________________________________
[gw0] win32 -- Python 2.7.13 c:\srv\venv\dktasklib\scripts\python.exe

ctx = <Context: <Config: {'tasks': {'search_root': None, 'collection_name': 'tasks',... None}, 'runners': {'local': <class 'invoke.runners.Local'>}, 'pkg': Package}>>

    def test_babel(ctx):
        files = """
            - package.json: |
                { "version": "1.1.2", "description": "",
                  "repository": "", "license": ""}
            - foo.js: |
                [1,2,3].map(x => x*x)
        """
        with create_files(files) as directory:
            ctx = ctx.init(pkg=Package())
            babel(
                ctx,
                'foo.js',
>               'foo-compiled.js',
            )

tests\test_jstools.py:24:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\venv\dktasklib\lib\site-packages\invoke\tasks.py:115: in __call__
    result = self.body(*args, **kwargs)
dktasklib\jstools.py:147: in babel
    ensure_es2015(ctx)
dktasklib\jstools.py:76: in ensure_es2015
    ctx.run("npm install babel-preset-es2015 --save-dev")
dktasklib\wintask.py:33: in run
    return _orig_run(self, command, **kwargs)
..\..\venv\dktasklib\lib\site-packages\invoke\context.py:82: in run
    return self._run(runner, command, **kwargs)
..\..\venv\dktasklib\lib\site-packages\invoke\context.py:89: in _run
    return runner.run(command, **kwargs)
..\..\venv\dktasklib\lib\site-packages\invoke\runners.py:262: in run
    return self._run_body(command, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <invoke.runners.Local object at 0x04A49490>
command = 'npm install babel-preset-es2015 --save-dev'
kwargs = {'buffer_': [], 'hide': False, 'output': <open file '<fdopen>', mode 'w' at 0x03B01F40>}
opts = {'echo': False, 'echo_stdin': None, 'encoding': None, 'env': {}, ...}
out_stream = <open file '<fdopen>', mode 'w' at 0x03B01F40>
err_stream = <open file '<fdopen>', mode 'w' at 0x03B01E90>
in_stream = <open file '<fdopen>', mode 'r' at 0x03B01EE8>
shell = 'C:\\WINDOWS\\system32\\cmd.exe'
env = {'ALLUSERSPROFILE': 'C:\\ProgramData', 'ANSICON': '254x3000 (254x63)', 'ANSICON_DEF': '7', 'APPDATA': 'C:\\Users\\bjorn\\AppData\\Roaming', ...}
stdout = []

    def _run_body(self, command, **kwargs):
        # Normalize kwargs w/ config
        opts, out_stream, err_stream, in_stream = self._run_opts(kwargs)
        shell = opts['shell']
        # Environment setup
        env = self.generate_env(opts['env'], opts['replace_env'])
        # Echo running command
        if opts['echo']:
            print("\033[1;37m{0}\033[0m".format(command))
        # Start executing the actual command (runs in background)
        self.start(command, shell, env)
        # Arrive at final encoding if neither config nor kwargs had one
        self.encoding = opts['encoding'] or self.default_encoding()
        # Set up IO thread parameters (format - body_func: {kwargs})
        stdout, stderr = [], []
        thread_args = {
            self.handle_stdout: {
                'buffer_': stdout,
                'hide': 'stdout' in opts['hide'],
                'output': out_stream,
            },
        }
        # After opt processing above, in_stream will be a real stream obj or
        # False, so we can truth-test it. We don't even create a stdin-handling
        # thread if it's False, meaning user indicated stdin is nonexistent or
        # problematic.
        if in_stream:
            thread_args[self.handle_stdin] = {
                'input_': in_stream,
                'output': out_stream,
                'echo': opts['echo_stdin'],
            }
        if not self.using_pty:
            thread_args[self.handle_stderr] = {
                'buffer_': stderr,
                'hide': 'stderr' in opts['hide'],
                'output': err_stream,
            }
        # Kick off IO threads
        self.threads = {}
        exceptions = []
        for target, kwargs in six.iteritems(thread_args):
            t = ExceptionHandlingThread(target=target, kwargs=kwargs)
            self.threads[target] = t
            t.start()
        # Wait for completion, then tie things off & obtain result
        # And make sure we perform that tying off even if things asplode.
        exception = None
        while True:
            try:
                self.wait()
                break # done waiting!
            # NOTE: we handle all this now instead of at
            # actual-exception-handling time because otherwise the stdout/err
            # reader threads may block until the subprocess exits.
            # TODO: honor other signals sent to our own process and transmit
            # them to the subprocess before handling 'normally'.
            except KeyboardInterrupt as e:
                self.send_interrupt(e)
                # NOTE: no break; we want to return to self.wait()
            except BaseException as e: # Want to handle SystemExit etc still
                # Store exception for post-shutdown reraise
                exception = e
                # Break out of return-to-wait() loop - we want to shut down
                break
        # Inform stdin-mirroring worker to stop its eternal looping
        self.program_finished.set()
        # Join threads, setting a timeout if necessary
        for target, thread in six.iteritems(self.threads):
            thread.join(self._thread_timeout(target))
            e = thread.exception()
            if e is not None:
                exceptions.append(e)
        # If we got a main-thread exception while wait()ing, raise it now that
        # we've closed our worker threads.
        if exception is not None:
            raise exception
        # Strip out WatcherError from any thread exceptions; they are bundled
        # into Failure handling at the end.
        watcher_errors = []
        thread_exceptions = []
        for exception in exceptions:
            real = exception.value
            if isinstance(real, WatcherError):
                watcher_errors.append(real)
            else:
                thread_exceptions.append(exception)
        # If any exceptions appeared inside the threads, raise them now as an
        # aggregate exception object.
        if thread_exceptions:
>           raise ThreadException(thread_exceptions)
E           ThreadException:
E           Saw 1 exceptions within threads (UnicodeEncodeError):
E
E
E           Thread args: {'kwargs': {'buffer_': [u'npm', u' ', u'WARN ', u'deprecated'],
E                       'hide': False,
E                       'output': <open file '<fdopen>', mode 'w' at 0x03B01E90>},
E            'target': <bound method Local.handle_stderr of <invoke.runners.Local object at 0x04A49490>>}
E
E           Traceback (most recent call last):
E
E             File "c:\srv\venv\dktasklib\lib\site-packages\invoke\util.py", line 202, in run
E               super(ExceptionHandlingThread, self).run()
E
E             File "c:\python27\Lib\threading.py", line 754, in run
E               self.__target(*self.__args, **self.__kwargs)
E
E             File "c:\srv\venv\dktasklib\lib\site-packages\invoke\runners.py", line 564, in handle_stderr
E               reader=self.read_proc_stderr,
E
E             File "c:\srv\venv\dktasklib\lib\site-packages\invoke\runners.py", line 522, in _handle_output
E               self.write_our_output(stream=output, string=data)
E
E             File "c:\srv\venv\dktasklib\lib\site-packages\invoke\runners.py", line 510, in write_our_output
E               stream.write(encode_output(string, self.encoding))
E
E             File "c:\srv\venv\dktasklib\lib\site-packages\invoke\util.py", line 143, in encode_output
E               string = string.encode(encoding)
E
E             File "c:\srv\venv\dktasklib\lib\encodings\cp1252.py", line 12, in encode
E               return codecs.charmap_encode(input,errors,encoding_table)
E
E           UnicodeEncodeError: 'charmap' codec can't encode character u'\ufffd' in position 500: character maps to <undefined>

..\..\venv\dktasklib\lib\site-packages\invoke\runners.py:356: ThreadException
==================== 1 failed, 27 passed in 20.06 seconds =====================
```

**Comment by bitprophet** [comment]
Offhand I feel it should've broken before that particular commit, since it doesn't actually change encoding so much as centralizes what was being done before. Both the before and after seem to perform non-fallback-specifying `encode()` calls.

Annoyingly, while I don't actually _look_ at Appveyor proactively, I just looked at it now (couldn't even remember if we had it set up - right - we do, it's Paramiko that lacks it still) and...the tests pass there: https://ci.appveyor.com/project/bitprophet/invoke/history

Can you reproduce this with Invoke's own test suite on your platform, @thebjorn? If not, can you suggest a test to add that does? Afraid I don't have time right now to think one up.

**Comment by thebjorn** [comment]
My test simply does `ctx.run("npm install babel-preset-es2015 --save-dev")` apparently while using `cp1252`:
```
E             File "c:\srv\venv\dktasklib\lib\encodings\cp1252.py", line 12, in encode
E               return codecs.charmap_encode(input,errors,encoding_table)
```
I don't know what's required to add a test that sets the encoding to cp1252 and runs the npm command, but I would imagine that such a test would break on linux too.

It seems way to hard to get windows fixes into the code base (ref #407) and I just don't have that kind of time at the moment (sorry, wish I did..).
