### ISSUE TITLE
pytest testing something that call invoke.Context.run leads to an IOError

### ISSUE THREAD

**Issue by zesk06** [pyinvoke/invoke#530]
The Context().run() capture the stdin, but py.test also capture stdin.
That leads to a ``IOError('reading from stdin while output is captured',)`` 

environment:
- python 2.7.5
- py.test 3.5.1

My pytest example:

```python
import invoke

"""launch this with py.test the_py_test_file.py"""
def test_invoke_with_pytest():
    invoke.Context().run('echo "hello world"')
```
This fails with the following error:
```bash
py.test tests/test_invoke.py
======================================================================================== test session starts =========================================================================================
platform linux2 -- Python 2.7.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/user/git/myproject, inifile: setup.cfg
plugins: xdist-1.22.2, pep8-1.0.6, forked-0.2, env-0.6.0, cov-2.5.1
collected 1 item

tests/test_invoke.py F                                                                                                                                                                         [100%]

============================================================================================== FAILURES ==============================================================================================
____________________________________________________________________________________________ test_invoke _____________________________________________________________________________________________

    def test_invoke():
>       invoke.Context().run('echo "hello world"')

tests/test_invoke.py:5:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../.virtualenvs/myproject/lib/python2.7/site-packages/invoke/context.py:93: in run
    return self._run(runner, command, **kwargs)
../../.virtualenvs/myproject/lib/python2.7/site-packages/invoke/context.py:100: in _run
    return runner.run(command, **kwargs)
../../.virtualenvs/myproject/lib/python2.7/site-packages/invoke/runners.py:268: in run
    return self._run_body(command, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <invoke.runners.Local object at 0x31967d0>, command = 'echo "hello world"', kwargs = {'buffer_': ['hello world
'], 'hide': False, 'output': <_pytest.capture.EncodedFile object at 0x2a7c910>}
opts = {'echo': False, 'echo_stdin': None, 'encoding': None, 'env': {}, ...}, out_stream = <_pytest.capture.EncodedFile object at 0x2a7c910>
err_stream = <_pytest.capture.EncodedFile object at 0x2a7c9d0>, in_stream = <_pytest.capture.DontReadFromInput object at 0x2a7c890>, shell = '/bin/bash'
env = {'ANT_HOME': '/opt/ant', 'CHROME_DESKTOP': 'Code.desktop', 'COLORTERM': 'gnome-terminal', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-u9J4BvKXMx,guid=b0edb635c5342c7cdc773e675af29ed7', ...}
stdout = ['hello world
']

    def _run_body(self, command, **kwargs):
        # Normalize kwargs w/ config
        opts, out_stream, err_stream, in_stream = self._run_opts(kwargs)
        shell = opts['shell']
        # Environment setup
        env = self.generate_env(opts['env'], opts['replace_env'])
        # Echo running command
        if opts['echo']:
            print("\033[1;37m{}\033[0m".format(command))
        # Start executing the actual command (runs in background)
        self.start(command, shell, env)
        # Arrive at final encoding if neither config nor kwargs had one
        self.encoding = opts['encoding'] or self.default_encoding()
        # Set up IO thread parameters (format - body_func: {kwargs})
        stdout, stderr = [], []
        thread_args = {
            self.handle_stdout: {
                'buffer_': stdout,
                'hide': 'stdout' in opts['hide'],
                'output': out_stream,
            },
        }
        # After opt processing above, in_stream will be a real stream obj or
        # False, so we can truth-test it. We don't even create a stdin-handling
        # thread if it's False, meaning user indicated stdin is nonexistent or
        # problematic.
        if in_stream:
            thread_args[self.handle_stdin] = {
                'input_': in_stream,
                'output': out_stream,
                'echo': opts['echo_stdin'],
            }
        if not self.using_pty:
            thread_args[self.handle_stderr] = {
                'buffer_': stderr,
                'hide': 'stderr' in opts['hide'],
                'output': err_stream,
            }
        # Kick off IO threads
        self.threads = {}
        exceptions = []
        for target, kwargs in six.iteritems(thread_args):
            t = ExceptionHandlingThread(target=target, kwargs=kwargs)
            self.threads[target] = t
            t.start()
        # Wait for completion, then tie things off & obtain result
        # And make sure we perform that tying off even if things asplode.
        exception = None
        while True:
            try:
                self.wait()
                break # done waiting!
            # NOTE: we handle all this now instead of at
            # actual-exception-handling time because otherwise the stdout/err
            # reader threads may block until the subprocess exits.
            # TODO: honor other signals sent to our own process and transmit
            # them to the subprocess before handling 'normally'.
            except KeyboardInterrupt as e:
                self.send_interrupt(e)
                # NOTE: no break; we want to return to self.wait()
            except BaseException as e: # Want to handle SystemExit etc still
                # Store exception for post-shutdown reraise
                exception = e
                # Break out of return-to-wait() loop - we want to shut down
                break
        # Inform stdin-mirroring worker to stop its eternal looping
        self.program_finished.set()
        # Join threads, setting a timeout if necessary
        for target, thread in six.iteritems(self.threads):
            thread.join(self._thread_timeout(target))
            e = thread.exception()
            if e is not None:
                exceptions.append(e)
        # If we got a main-thread exception while wait()ing, raise it now that
        # we've closed our worker threads.
        if exception is not None:
            raise exception
        # Strip out WatcherError from any thread exceptions; they are bundled
        # into Failure handling at the end.
        watcher_errors = []
        thread_exceptions = []
        for exception in exceptions:
            real = exception.value
            if isinstance(real, WatcherError):
                watcher_errors.append(real)
            else:
                thread_exceptions.append(exception)
        # If any exceptions appeared inside the threads, raise them now as an
        # aggregate exception object.
        if thread_exceptions:
>           raise ThreadException(thread_exceptions)
E           ThreadException:
E           Saw 1 exceptions within threads (IOError):
E
E
E           Thread args: {'kwargs': {'echo': None,
E                       'input_': <_pytest.capture.DontReadFromInput object at 0x2a7c890>,
E                       'output': <_pytest.capture.EncodedFile object at 0x2a7c910>},
E            'target': <bound method Local.handle_stdin of <invoke.runners.Local object at 0x31967d0>>}
E
E           Traceback (most recent call last):
E
E             File "/home/user/.virtualenvs/myproject/lib/python2.7/site-packages/invoke/util.py", line 232, in run
E               super(ExceptionHandlingThread, self).run()
E
E             File "/usr/lib64/python2.7/threading.py", line 765, in run
E               self.__target(*self.__args, **self.__kwargs)
E
E             File "/home/user/.virtualenvs/myproject/lib/python2.7/site-packages/invoke/runners.py", line 644, in handle_stdin
E               data = self.read_our_stdin(input_)
E
E             File "/home/user/.virtualenvs/myproject/lib/python2.7/site-packages/invoke/runners.py", line 604, in read_our_stdin
E               bytes_ = input_.read(bytes_to_read(input_))
E
E             File "/home/user/.virtualenvs/myproject/lib/python2.7/site-packages/_pytest/capture.py", line 574, in read
E               raise IOError("reading from stdin while output is captured")
E
E           IOError: reading from stdin while output is captured

../../.virtualenvs/myproject/lib/python2.7/site-packages/invoke/runners.py:362: ThreadException
---------------------------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------------------------
hello world
---------------------------------------------------------------------------------------- Captured stderr call ----------------------------------------------------------------------------------------
DEBUG:invoke:Didn't see any /etc/invoke.yaml, skipping.
DEBUG:invoke:Didn't see any /etc/invoke.yml, skipping.
DEBUG:invoke:Didn't see any /etc/invoke.json, skipping.
DEBUG:invoke:Didn't see any /home/user/.invoke.yaml, skipping.
DEBUG:invoke:Didn't see any /home/user/.invoke.yml, skipping.
DEBUG:invoke:Didn't see any /home/user/.invoke.json, skipping.
DEBUG:invoke:Merging config sources in order onto new empty _config...
DEBUG:invoke:Defaults: {'run': {'shell': '/bin/bash', 'hide': None, 'env': {}, 'replace_env': False, 'in_stream': None, 'encoding': None, 'echo': False, 'warn': False, 'echo_stdin': None, 'watchers': [], 'pty': False, 'out_stream': None, 'err_stream': None, 'fallback': True}, 'tasks': {'search_root': None, 'collection_name': 'tasks', 'dedupe': True, 'auto_dash_names': True}, 'sudo': {'password': None, 'prompt': '[sudo] password: ', 'user': None}, 'runners': {'local': <class 'invoke.runners.Local'>}}
DEBUG:invoke:Collection-driven: {}
DEBUG:invoke:System-wide config file (/etc/invoke.py): {}
DEBUG:invoke:Per-user config file (/home/user/.invoke.py): {}
DEBUG:invoke:Per-project config file has not been loaded yet, skipping
DEBUG:invoke:Environment variable config: {}
DEBUG:invoke:Runtime config file has not been loaded yet, skipping
DEBUG:invoke:Overrides: {}
DEBUG:invoke:Modifications: {}
DEBUG:invoke:Deletions: {}
DEBUG:invoke:Encountered exception IOError('reading from stdin while output is captured',) in thread for 'handle_stdin'
----------------------------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------------------------
config.py                  885 DEBUG    Didn't see any /etc/invoke.yaml, skipping.
config.py                  885 DEBUG    Didn't see any /etc/invoke.yml, skipping.
config.py                  885 DEBUG    Didn't see any /etc/invoke.json, skipping.
config.py                  885 DEBUG    Didn't see any /home/user/.invoke.yaml, skipping.
config.py                  885 DEBUG    Didn't see any /home/user/.invoke.yml, skipping.
config.py                  885 DEBUG    Didn't see any /home/user/.invoke.json, skipping.
config.py                  920 DEBUG    Merging config sources in order onto new empty _config...
config.py                  922 DEBUG    Defaults: {'run': {'shell': '/bin/bash', 'hide': None, 'env': {}, 'replace_env': False, 'in_stream': None, 'encoding': None, 'echo': False, 'warn': False, 'echo_stdin': None, 'watchers': [], 'pty': False, 'out_stream': None, 'err_stream': None, 'fallback': True}, 'tasks': {'search_root': None, 'collection_name': 'tasks', 'dedupe': True, 'auto_dash_names': True}, 'sudo': {'password': None, 'prompt': '[sudo] password: ', 'user': None}, 'runners': {'local': <class 'invoke.runners.Local'>}}
config.py                  924 DEBUG    Collection-driven: {}
config.py                  950 DEBUG    System-wide config file (/etc/invoke.py): {}
config.py                  950 DEBUG    Per-user config file (/home/user/.invoke.py): {}
config.py                  947 DEBUG    Per-project config file has not been loaded yet, skipping
config.py                  929 DEBUG    Environment variable config: {}
config.py                  947 DEBUG    Runtime config file has not been loaded yet, skipping
config.py                  932 DEBUG    Overrides: {}
config.py                  934 DEBUG    Modifications: {}
config.py                  936 DEBUG    Deletions: {}
util.py                    244 DEBUG    Encountered exception IOError('reading from stdin while output is captured',) in thread for 'handle_stdin'
====================================================================================== 1 failed in 0.08 seconds ===========================================
```

As a workaround, I used a fake ``in_stream`` using ``StringIO``
```python
import invoke
import StringIO


def test_invoke():
    invoke.Context().run('echo "hello world"',
                         in_stream=StringIO.StringIO(''))
```

**Comment by bitprophet** [comment]
This is a common problem with pytest, we have it ourselves! You can just say `in_stream=False`, by the way, it's the designated method of turning off stdin mirroring entirely - see `in_stream` in the API docs for `run`: http://docs.pyinvoke.org/en/1.0/api/runners.html#invoke.runners.Runner.run

I'm open to suggestions to make this more flexible; squashing IOError entirely makes me uncomfortable since it'd be quite bad in the default case of _not_ running under pytest, but perhaps turning it into a `warnings` based warn-and-continue might be acceptable for example.
