### ISSUE TITLE
Dependent tasks in the same nested namespace get the wrong config, if called from outer namespace

### ISSUE THREAD

**Issue by zypus** [pyinvoke/invoke#548]
Considering the following demo code, slightly modified from the [documentation](http://docs.pyinvoke.org/en/1.0/api/tasks.html?highlight=called_As#invoke.tasks.call):

```
from invoke import Collection, task, Call
   
# This task & collection could just as easily come from
# another module somewhere.
@task
def mytask(c):
    print(c['conflicted'])
   
@task(mytask)
def mytask2(c):
   print(c['conflicted'])

inner = Collection('inner', mytask, mytask2)
inner.configure({'conflicted': 'default value'})
   
 # Our project's root namespace.
ns = Collection(inner)
```

Calling `invoke inner.mytask2` results in:
```
 Traceback (most recent call last):
  File "D:\Programs\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Programs\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Programs\Anaconda3\lib\site-packages\invoke\__main__.py", line 3, in <module>
    program.run()
  File "D:\Programs\Anaconda3\lib\site-packages\invoke\program.py", line 332, in run
    self.execute()
  File "D:\Programs\Anaconda3\lib\site-packages\invoke\program.py", line 480, in execute
    executor.execute(*self.tasks)
  File "D:\Programs\Anaconda3\lib\site-packages\invoke\executor.py", line 133, in execute
    result = call.task(*args, **call.kwargs)
  File "...\invoke\tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "...\scripts\test\tasks.py", line 8, in mytask
    print(c['conflicted'])
  File "D:\Programs\Anaconda3\lib\site-packages\invoke\config.py", line 154, in __getitem__
    return self._get(key)
  File "D:\Programs\Anaconda3\lib\site-packages\invoke\config.py", line 165, in _get
    value = self._config[key]
  File "D:\Programs\Anaconda3\lib\site-packages\invoke\config.py", line 154, in __getitem__
    return self._get(key)
  File "D:\Programs\Anaconda3\lib\site-packages\invoke\config.py", line 165, in _get
    value = self._config[key]
KeyError: 'conflicted'
```

What we would have expected:
default value
default value

By taking a look at the source code, we suspect this line in the [executor](https://github.com/pyinvoke/invoke/blob/master/invoke/executor.py#L125) causes this issue:
`collection_config = self.collection.configuration(call.called_as)`

The configuration resolution retrieved the outer namespace config ie. no config for the `mytask` task, because `mytask2` refers to `mytask` without specifying the namespace.

A workaround would be to specify the pre task dependency explicitly by including the namespace in the `called_as` parameter of the Call object:
```
@task(pre=[Call(mytask, called_as="inner.mytask")])
def mytask2(c):
    print(c['conflicted'])
```

But in general a task mustn't need to know its namespace.

This currently prevents us from reusing shared task with dependencies where we want to keep some of the nested namespace configuration. 
The problem is hidden if the nesting namespace provides values for all members of the nested config.

**Comment by offbyone** [comment]
I have a nice minimal reproduction case for this, since I'm running into it myself:

```python
from invoke import task, Collection


@task
def reused(c):
    print(c["config_key"])


@task(pre=[reused])
def leaf(c):
    ...


col1 = Collection("c1", reused, leaf)
col1.configure({"config_key": "val1"})
ns = Collection(col1)
```

This results in: 

```
$ inv c1.reused
val1

$ inv c1.leaf
Traceback (most recent call last):
  File "/Users/offby1/tmp/t-invoke/.venv/bin/inv", line 8, in <module>
    sys.exit(program.run())
  File "/Users/offby1/tmp/t-invoke/.venv/lib/python3.9/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/Users/offby1/tmp/t-invoke/.venv/lib/python3.9/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/Users/offby1/tmp/t-invoke/.venv/lib/python3.9/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/Users/offby1/tmp/t-invoke/.venv/lib/python3.9/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/offby1/tmp/t-invoke/tasks.py", line 6, in reused
    print(c["config_key"])
  File "/Users/offby1/tmp/t-invoke/.venv/lib/python3.9/site-packages/invoke/config.py", line 167, in __getitem__
    return self._get(key)
  File "/Users/offby1/tmp/t-invoke/.venv/lib/python3.9/site-packages/invoke/config.py", line 176, in _get
    value = self._config[key]
  File "/Users/offby1/tmp/t-invoke/.venv/lib/python3.9/site-packages/invoke/config.py", line 167, in __getitem__
    return self._get(key)
  File "/Users/offby1/tmp/t-invoke/.venv/lib/python3.9/site-packages/invoke/config.py", line 176, in _get
    value = self._config[key]
KeyError: 'config_key'
```
