### ISSUE TITLE
Exception when forgetting the name keyword argument

### ISSUE THREAD

**Issue by thedrow** [pyinvoke/invoke#598]
I have a task `foo` which is a pre-task of `bar`:
```python
@task('name')
def foo(ctx):
   # ...

@task(pre=[foo])
def bar(ctx):
  # ...
```
I think that because I forgot the name keyword argument I got the error below.
The error is similar to #160:
```
Traceback (most recent call last):
  File "/home/omer/.local/share/virtualenvs/project-Tyh2l4b_/bin/inv", line 11, in <module>
    sys.exit(program.run())
  File "/home/omer/.local/share/virtualenvs/project-Tyh2l4b_/lib/python3.7/site-packages/invoke/program.py", line 363, in run
    self.execute()
  File "/home/omer/.local/share/virtualenvs/project-Tyh2l4b_/lib/python3.7/site-packages/invoke/program.py", line 532, in execute
    executor.execute(*self.tasks)
  File "/home/omer/.local/share/virtualenvs/project-Tyh2l4b_/lib/python3.7/site-packages/invoke/executor.py", line 95, in execute
    expanded = self.expand_calls(calls)
  File "/home/omer/.local/share/virtualenvs/project-Tyh2l4b_/lib/python3.7/site-packages/invoke/executor.py", line 209, in expand_calls
    ret.extend(self.expand_calls(call.pre))
  File "/home/omer/.local/share/virtualenvs/project-Tyh2l4b_/lib/python3.7/site-packages/invoke/executor.py", line 209, in expand_calls
    ret.extend(self.expand_calls(call.pre))
  File "/home/omer/.local/share/virtualenvs/project-Tyh2l4b_/lib/python3.7/site-packages/invoke/executor.py", line 209, in expand_calls
    ret.extend(self.expand_calls(call.pre))
AttributeError: 'str' object has no attribute 'pre
```
 
The error should be clearer to ease debugging.

**Comment by haydenflinner** [comment]
I fixed this in my local version of `invoke`, you can try it yourself with `pip install magicinvoke`, until the fix gets merged here :smile: If you just want to patch your version, here's the diff

```python
──────────────────────────────────────────────────────────────────────────────────────
modified: invoke/tasks.py
──────────────────────────────────────────────────────────────────────────────────────
@ tasks.py:89 @ class Task(object):
        self.pre = pre or []
        self.skip_ifs = skip_ifs or []
        self.post = post or []
        self.__should_be_task_list(self.pre, 'pre')
        self.__should_be_task_list(self.skip_ifs, 'skip_ifs')
        self.__should_be_task_list(self.post, 'post')
 
        self.times_called = 0
        # Whether to print return value post-execution
        self.autoprint = autoprint

 
    def __should_be_task_list(self, l, l_name):
        # Is it a list?
        if not hasattr(l, "__iter__"):
            err = ("Expected iterable! Did you do {l}=mytask instead of {l}=[mytask]?"
            .format(l=l_name))
            raise ValueError(err)
        # Is each item in the list a task?
        for task in l:
            if not hasattr(task, 'pre'):
                err = ("'{s}' has no attr pre!\nDid you mean "
                "@task({s}) instead of @task('{s}')?"
                "Are you sure {s} is an invoke.task?"
                .format(s=task))
                raise ValueError(err)
```
