### ISSUE TITLE
Failed on just run invoke ver 1.2.0 on python3.6 on MacOS

### ISSUE THREAD

**Issue by viethungnguyen-grab** [pyinvoke/invoke#641]
```python
$ cat tasks.py
from invoke import task

@task
def build():
    print("Building!")
```

```
(proj) hvnsweeting@VNMAC: ~/me/proj (master) $ invoke --version
Invoke 1.2.0
(proj) hvnsweeting@VNMAC: ~/me/proj (master) $ invoke build
Traceback (most recent call last):
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/tasks.py", line 160, in argspec
    context_arg = arg_names.pop(0)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hvnsweeting/Envs/proj/bin/invoke", line 10, in <module>
    sys.exit(program.run())
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/program.py", line 352, in run
    self.parse_collection()
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/program.py", line 444, in parse_collection
    self.load_collection()
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/program.py", line 661, in load_collection
    module, parent = loader.load(coll_name)
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hvnsweeting/grab/proj/tasks.py", line 3, in <module>
    @task
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/tasks.py", line 313, in task
    return klass(args[0], **kwargs)
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/tasks.py", line 77, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/tasks.py", line 168, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/tasks.py", line 163, in argspec
    raise TypeError("Tasks must have an initial Context argument!")
TypeError: Tasks must have an initial Context argument!

(proj) hvnsweeting@VNMAC: ~/me/proj (master) $ invoke
Traceback (most recent call last):
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/tasks.py", line 160, in argspec
    context_arg = arg_names.pop(0)
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hvnsweeting/Envs/proj/bin/invoke", line 10, in <module>
    sys.exit(program.run())
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/program.py", line 352, in run
    self.parse_collection()
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/program.py", line 444, in parse_collection
    self.load_collection()
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/program.py", line 661, in load_collection
    module, parent = loader.load(coll_name)
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hvnsweeting/grab/proj/tasks.py", line 3, in <module>
    @task
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/tasks.py", line 313, in task
    return klass(args[0], **kwargs)
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/tasks.py", line 77, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/tasks.py", line 168, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/Users/hvnsweeting/Envs/proj/lib/python3.6/site-packages/invoke/tasks.py", line 163, in argspec
    raise TypeError("Tasks must have an initial Context argument!")
TypeError: Tasks must have an initial Context argument!
```

**Comment by shlomiLan** [comment]
Look at the line `TypeError: Tasks must have an initial Context argument!`, you need to add a context variable to your task. see here: http://www.pyinvoke.org/  at the var `c` that is passed to the tasks.
