### ISSUE TITLE
Support Python 3 type annotation

### ISSUE THREAD

**Issue by ayushkovskiy** [pyinvoke/invoke#664]
The following target does not work:
```
@task
def setup(context: invoke.context.Context):
    pass
```
```
Traceback (most recent call last):
  File "/home/username/.pyenv/versions/3.6.3-debug/bin/inv", line 10, in <module>
    sys.exit(program.run())
  File "/home/username/.pyenv/versions/3.6.3-debug/lib/python3.6/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/home/username/.pyenv/versions/3.6.3-debug/lib/python3.6/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/home/username/.pyenv/versions/3.6.3-debug/lib/python3.6/site-packages/invoke/program.py", line 696, in load_collection
    module, parent = loader.load(coll_name)
  File "/home/username/.pyenv/versions/3.6.3-debug/lib/python3.6/site-packages/invoke/loader.py", line 76, in load
    module = imp.load_module(name, fd, path, desc)
  File "/home/username/.pyenv/versions/3.6.3-debug/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/username/.pyenv/versions/3.6.3-debug/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/username/github/nm/platform-template/neuro-shortcuts/tasks.py", line 40, in <module>
    def setup(context: invoke.context.Context):
  File "/home/username/.pyenv/versions/3.6.3-debug/lib/python3.6/site-packages/invoke/tasks.py", line 312, in task
    return klass(args[0], **kwargs)
  File "/home/username/.pyenv/versions/3.6.3-debug/lib/python3.6/site-packages/invoke/tasks.py", line 76, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/home/username/.pyenv/versions/3.6.3-debug/lib/python3.6/site-packages/invoke/tasks.py", line 167, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/home/username/.pyenv/versions/3.6.3-debug/lib/python3.6/site-packages/invoke/tasks.py", line 153, in argspec
    spec = inspect.getargspec(func)
  File "/home/username/.pyenv/versions/3.6.3-debug/lib/python3.6/inspect.py", line 1072, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them
```

**Comment by ayushkovskiy** [comment]
duplicate of https://github.com/pyinvoke/invoke/issues/357 (see also PR https://github.com/pyinvoke/invoke/pull/606)
