### ISSUE TITLE
Pre task in collection does not get collection config

### ISSUE THREAD

**Issue by grangerp** [pyinvoke/invoke#736]
In this simple example:
```python
from invoke import Collection, task

@task
def pre_task(c):
    print(c["conflicted"])

@task(pre=[pre_task])
def mytask(c):
    print(c["conflicted"])

inner = Collection("inner", mytask, pre_task)
inner.configure({"conflicted": "default value"})

# Our project's root namespace.
ns = Collection(inner)
ns.configure({})
```
I get an error when I call:
```console
$ inv inner.mytask 
Traceback (most recent call last):
  File "/home/pgranger/.local/bin/inv", line 8, in <module>
    sys.exit(program.run())
  File "/home/pgranger/.local/pipx/venvs/invoke/lib/python3.8/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/home/pgranger/.local/pipx/venvs/invoke/lib/python3.8/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/home/pgranger/.local/pipx/venvs/invoke/lib/python3.8/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/pgranger/.local/pipx/venvs/invoke/lib/python3.8/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/pgranger/Downloads/testinv/tasks.py", line 6, in pre_task
    print(c["conflicted"])
  File "/home/pgranger/.local/pipx/venvs/invoke/lib/python3.8/site-packages/invoke/config.py", line 167, in __getitem__
    return self._get(key)
  File "/home/pgranger/.local/pipx/venvs/invoke/lib/python3.8/site-packages/invoke/config.py", line 176, in _get
    value = self._config[key]
  File "/home/pgranger/.local/pipx/venvs/invoke/lib/python3.8/site-packages/invoke/config.py", line 167, in __getitem__
    return self._get(key)
  File "/home/pgranger/.local/pipx/venvs/invoke/lib/python3.8/site-packages/invoke/config.py", line 176, in _get
    value = self._config[key]
KeyError: 'conflicted'
```
But calling directly pre-task work as expected:
```console
$ inv inner.pre-task 
default value
```
Not sure if this is a bug or if I am doing something wrong.

**Comment by grangerp** [comment]
I have tested with py36,py37 and py38, same results.

**Comment by alexandre-perrin** [comment]
I could only find this workaround: https://github.com/pyinvoke/invoke/issues/781#issuecomment-759405830

**Comment by surry** [comment]
I looked into this and think the issue is here:

https://github.com/pyinvoke/invoke/blob/ed94c59f1eacc700dac3815530493e0809fe001d/invoke/executor.py#L199

When the `pre`/`post` tasks are expanded, there doesn't seem to be any knowledge of which collection they come from, so `called_as` is not set here, unlike on L155 for the main task that is invoked on the command-line:

https://github.com/pyinvoke/invoke/blob/ed94c59f1eacc700dac3815530493e0809fe001d/invoke/executor.py#L155

Maybe there is some way to get the collection associated with the `pre` task, but I'm not seeing it right now. Especially since the pre task could be imported from another module. Also, just based on the way tasks are registered with `@task`, it doesn't seem like there would be a way to get the appropriate collection to generate the right `called_as` argument automatically, since a @task could be included in multiple collections...

**Comment by retnuh** [comment]
Any update on this?  Just lost a couple hours tracking this surprising behaviour down.  Maybe the code structure has changed enough in `2.2.x` to make a fix more straight forwards?
