### ISSUE TITLE
Documentation is too light on how to use custom runners

### ISSUE THREAD

**Issue by pawamoy** [pyinvoke/invoke#757]
I read through many pages of the documentation and I came to the conclusion that I have to modify the `runners` configuration in the context object if I want to use a custom runner for a particular task. But I don't know what to put in the config item.

> The runners tree controls _which_ runner classes map to which execution contexts; if you’re using Invoke by itself, this will only tend to have a single member, runners.local. Client libraries may extend it with additional key/value pairs, such as runners.remote.

So, it's a dict ("tree")? I guess the keys are the execution contexts? What are they?

```python
@task
def mytask(context):
    context.config["runners"] = {...}  # ?
    # maybe I can do this as well?
    context.config.runners = {...}  # ?
```

We have this in the source code:

https://github.com/pyinvoke/invoke/blob/master/invoke/config.py#L493

```python
    "runners": {"local": Local},
```

Okay so theoretically I could override my config like this:

```python
@task
def mytask(context):
    context.config.runners = {"local": MyCustomRunner}
```

But when I execute the task I get this traceback:

```
Traceback (most recent call last):
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/pawamoy-testing-MLPX4Zaj-py3.6/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/pawamoy-testing-MLPX4Zaj-py3.6/lib/python3.6/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/pawamoy-testing-MLPX4Zaj-py3.6/lib/python3.6/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/pawamoy-testing-MLPX4Zaj-py3.6/lib/python3.6/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/pawamoy-testing-MLPX4Zaj-py3.6/lib/python3.6/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/media/data/dev/pawamoy/copier-poetry/tests/tmp/tasks/__init__.py", line 147, in docs_regen
    context.run(function)
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/pawamoy-testing-MLPX4Zaj-py3.6/lib/python3.6/site-packages/invoke/context.py", line 94, in run
    return self._run(runner, command, **kwargs)
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/pawamoy-testing-MLPX4Zaj-py3.6/lib/python3.6/site-packages/invoke/context.py", line 100, in _run
    command = self._prefix_commands(command)
  File "/home/pawamoy/.cache/pypoetry/virtualenvs/pawamoy-testing-MLPX4Zaj-py3.6/lib/python3.6/site-packages/invoke/context.py", line 246, in _prefix_commands
    return " && ".join(prefixes + [command])
TypeError: sequence item 0: expected str instance, function found
```

Indeed, here are the `run` methods of the context object:

```python
    def run(self, command, **kwargs):
        runner = self.config.runners.local(self)
        return self._run(runner, command, **kwargs)

    def _run(self, runner, command, **kwargs):
        command = self._prefix_commands(command)
        return runner.run(command, **kwargs)
```

So it's not enough because I wanted my custom runner to accept a Python function instead of a command, but it won't work since the context object tries to prefix it as if it was a string. It means I have to modify the context object as well.

I eventually replaced the whole `context.run` function, but then it seems that task don't fail anymore, even if I forcefully return an fake exit code 1.

**Comment by pawamoy** [comment]
What I was trying to do was what is described in #754, see the last comment in this issue.
