### ISSUE TITLE
invoke fail in Python 3.10 while parsing yaml configuration.

### ISSUE THREAD

**Issue by falsetru** [pyinvoke/invoke#820]
Running `inv(oke)` in Python 3.10 raises exceptions, while parsing yaml configuration.

## How to reproduce

1. Install invoke in Python 3.10 env.

    ```
    python3.10 -m venv .venv
    source .venv/bin/activate
    pip install invoke==1.6.0
    ```

1. Make a dummy `tasks.py`:

    ```
    touch tasks.py
    ```

1. Make a `invoke.yml`:

    ```
    echo 'debug: true' > invoke.yml
    ```

1. Run invoke

    ```
    inv
    ```

## Expected behavior

Run without error

## Actual behavior

fail with exception
```
(.venv) ➜  invoke-test inv
Traceback (most recent call last):
  File "/tmp/invoke-test/.venv/bin/inv", line 8, in <module>
    sys.exit(program.run())
  File "/tmp/invoke-test/.venv/lib/python3.10/site-packages/invoke/program.py", line 373, in run
    self.parse_collection()
  File "/tmp/invoke-test/.venv/lib/python3.10/site-packages/invoke/program.py", line 465, in parse_collection
    self.load_collection()
  File "/tmp/invoke-test/.venv/lib/python3.10/site-packages/invoke/program.py", line 702, in load_collection
    self.config.load_project()
  File "/tmp/invoke-test/.venv/lib/python3.10/site-packages/invoke/config.py", line 750, in load_project
    self._load_file(prefix="project", merge=merge)
  File "/tmp/invoke-test/.venv/lib/python3.10/site-packages/invoke/config.py", line 889, in _load_file
    self._set(data, loader(filepath))
  File "/tmp/invoke-test/.venv/lib/python3.10/site-packages/invoke/config.py", line 912, in _load_yml
    return self._load_yaml(path)
  File "/tmp/invoke-test/.venv/lib/python3.10/site-packages/invoke/config.py", line 909, in _load_yaml
    return yaml.load(fd)
  File "/tmp/invoke-test/.venv/lib/python3.10/site-packages/invoke/vendor/yaml3/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/tmp/invoke-test/.venv/lib/python3.10/site-packages/invoke/vendor/yaml3/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/tmp/invoke-test/.venv/lib/python3.10/site-packages/invoke/vendor/yaml3/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/tmp/invoke-test/.venv/lib/python3.10/site-packages/invoke/vendor/yaml3/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/tmp/invoke-test/.venv/lib/python3.10/site-packages/invoke/vendor/yaml3/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/tmp/invoke-test/.venv/lib/python3.10/site-packages/invoke/vendor/yaml3/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'
```

**Comment by falsetru** [comment]
https://github.com/pyinvoke/invoke/pull/803 solved the issue.

```
pip install --force-reinstall git+https://github.com/andir/invoke.git@e74e2a4743b18088afcbfb74f0d7ec5dd20a2652
```

**Comment by davidalo** [comment]
Having the same issue.

**Comment by idlesign** [comment]
The same here on Python 3.10: vendored yaml library is not compatible.

```
/home/runner/work/webscaff/webscaff/.eggs/invoke-1.6.0-py3.10.egg/invoke/config.py:909: in _load_yaml
    return yaml.load(fd)
/home/runner/work/webscaff/webscaff/.eggs/invoke-1.6.0-py3.10.egg/invoke/vendor/yaml3/__init__.py:72: in load
    return loader.get_single_data()
/home/runner/work/webscaff/webscaff/.eggs/invoke-1.6.0-py3.10.egg/invoke/vendor/yaml3/constructor.py:37: in get_single_data
    return self.construct_document(node)
/home/runner/work/webscaff/webscaff/.eggs/invoke-1.6.0-py3.10.egg/invoke/vendor/yaml3/constructor.py:46: in construct_document
    for dummy in generator:
/home/runner/work/webscaff/webscaff/.eggs/invoke-1.6.0-py3.10.egg/invoke/vendor/yaml3/constructor.py:398: in construct_yaml_map
    value = self.construct_mapping(node)
/home/runner/work/webscaff/webscaff/.eggs/invoke-1.6.0-py3.10.egg/invoke/vendor/yaml3/constructor.py:204: in construct_mapping
    return super().construct_mapping(node, deep=deep)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <invoke.vendor.yaml3.loader.Loader object at 0x7fcbbb54f6a0>
node = MappingNode(tag='tag:yaml.org,2002:map', value=[(ScalarNode(tag='tag:yaml.org,2002:str', value='remotes'), ScalarNode(...e(tag='tag:yaml.org,2002:str', value='email'), ScalarNode(tag='tag:yaml.org,2002:str', value='idlesign@some.com'))]))])
deep = False

    def construct_mapping(self, node, deep=False):
        if not isinstance(node, MappingNode):
            raise ConstructorError(None, None,
                    "expected a mapping node, but found %s" % node.id,
                    node.start_mark)
        mapping = {}
        for key_node, value_node in node.value:
            key = self.construct_object(key_node, deep=deep)
>           if not isinstance(key, collections.Hashable):
E           AttributeError: module 'collections' has no attribute 'Hashable'
```
See #803 for a possible solution.

@bitprophet Jeff, any progress on that?

**Comment by marcelofern** [comment]
Same issue.

**Comment by bitprophet** [comment]
See #803
