### ISSUE TITLE
Any pipe breaks inv -l when the task name is too long

### ISSUE THREAD

**Issue by FlorentJeannot** [pyinvoke/invoke#865]
My config is:
- macOS 12.4 (21F79)
- Python 3.9.12
- invoke 1.7.1

When the task reaches 74 characters, it's not possible to use a pipe with `inv -l`(the command still works on its own).
While it is unlikely to have a name as long as 74 characters, it is possible to have something like `{collection_name}.{task_name}.{action}` which goes up to 74 characters.

I suspect the issue to be in there: https://github.com/pyinvoke/invoke/blob/main/invoke/terminals.py#L56

Example:

```python
from invoke import task

name = 'a' * 74

@task(name=name)
def my_task(ctx):
    pass
```

```
inv -l | grep a
Traceback (most recent call last):
  File "/Users/florent/PycharmProjects/test/.venv/bin/inv", line 8, in <module>
Available tasks:
    sys.exit(program.run())
  File "/Users/florent/PycharmProjects/test/.venv/lib/python3.9/site-packages/invoke/program.py", line 377, in run
    self.parse_cleanup()
  File "/Users/florent/PycharmProjects/test/.venv/lib/python3.9/site-packages/invoke/program.py", line 516, in parse_cleanup
    self.list_tasks()
  File "/Users/florent/PycharmProjects/test/.venv/lib/python3.9/site-packages/invoke/program.py", line 790, in list_tasks
    getattr(self, "list_{}".format(self.list_format))()
  File "/Users/florent/PycharmProjects/test/.venv/lib/python3.9/site-packages/invoke/program.py", line 794, in list_flat
    self.display_with_columns(pairs=pairs)
  File "/Users/florent/PycharmProjects/test/.venv/lib/python3.9/site-packages/invoke/program.py", line 901, in display_with_columns
    self.print_columns(pairs)
  File "/Users/florent/PycharmProjects/test/.venv/lib/python3.9/site-packages/invoke/program.py", line 936, in print_columns
    help_chunks = wrapper.wrap(help_str)
  File "/Users/florent/.pyenv/versions/3.9.12/lib/python3.9/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/Users/florent/.pyenv/versions/3.9.12/lib/python3.9/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width 0 (must be > 0)
```

**Comment by hellojappie** [comment]
Can confirm. This happened to me when I set a few legacy aliases for similar tasks. It works properly when the terminal is wide enough for everything to fit without breaking any lines. I see an error, similar to the one above, when the terminal is too narrow.
